version: '3.1'
services:
  db:
    image: 'mongo'
    container_name: db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=abc123
    restart: always
    ports:
      - '27017:27017'
